### PR TITLE
MSSB-43: Event calendar contrast

### PR DESCRIPTION
**Pull request by CocoaBean5**
## JIRA Ticket(s)

- See ticket https://palantir.atlassian.net/browse/MSSB-43

## Description

- Branch from https://github.com/palantirnet/st-bernards/pull/6
- Changed button text color
Screen Shot 2020-01-16 at 3 51 31 PM
- Changed colors of the events to pass WCAG standards
(examples:)
Screen Shot 2020-01-16 at 4 29 24 PM
Screen Shot 2020-01-16 at 4 33 11 PM

## Testing instructions

Before - 
Screen Shot 2020-01-16 at 6 03 05 PM
After - 
Screen Shot 2020-01-16 at 6 02 47 PM
(two errors on hidden elements)

- Navigate to `cd web/themes/custom/blrfurther_d8`, run `gulp sass` to compile CSS.
- `drush cim`
- `drush cr`
- Visit http://st-bernards.local/events and make sure the colors pass a11y standards.

### CODE REVIEW

**Comment by russom-woldezghi** [comment]
@CocoaBean5 Can you look into these merge conflicts?

**Comment by russom-woldezghi** [comment]
@CocoaBean5 I am able confirm the number of contrast errors are down to two. I did notice the two  are for the "Month/List" and "Today" buttons. They are little hard to see currently, unless a user is focusing or clicking on them. Is it possible to improve the contrast on those two buttons?

**Comment by megansabina** [comment]
@CocoaBean5  - See Russ's comment above about two remaining buttons.

**Comment by CocoaBean5** [comment]
Compiled CSS locally and it works with existing code. Updated testing instructions, and rearranged the file structure to better suit other work that has been done.
Screen Shot 2020-02-03 at 4 53 52 PM

**Pull request merged**
